//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb1
    {
        public string tb11 { get; set; }
        public string tbname { get; set; }
    }
}
